---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/ffocolmy/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp stylesheet.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp IATF.png $DEPLOYPATH
    - /bin/cp ISO.png $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH
    - /bin/cp /gallery/* $DEPLOYPATH


